GCP/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('gcpapp.views',

    url(r'^$', 'home', name='home'),
    url(r'^about/$', 'about', name='about'),
    url(r'^green_groups/$', 'green_groups', name='green_groups'),
    url(r'^resources/$', 'resources', name='resources'),
    url(r'^reports/$', 'reports', name='reports'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^signup/$', 'signup', name='signup'),
    url(r'^accounts/login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    
    #SUPERUSER SECTION
    url(r'^superuser/$', 'superuser_content', name='superuser'),
    url(r'^superuser/verify/$', 'superuser_verify', name='superuser_verify'),
    url(r'^superuser/academic_year/$', 'superuser_academic_year', name='superuser_academic_year'),
    url(r'^superuser/questions/$', 'superuser_questions', name='superuser_questions'),
    url(r'^superuser/questions/edit/$', 'superuser_questions_edit'),
    url(r'^superuser/staff/$', 'superuser_staff', name='superuser_staff'),
    url(r'^superuser/staff/(?P<user_id>\d+)/$', 'superuser_staff_user', name='superuser_staff_user'),
    url(r'^superuser/staff/create/$', 'superuser_staff_create', name='superuser_staff_create'),
    url(r'^superuser/all_accounts/$', 'superuser_all_accounts', name='superuser_all_accounts'),
    url(r'^superuser/finance/$', 'superuser_finance', name='superuser_finance'),
    url(r'^superuser/finance/(?P<finance_id>\d+)/$', 'superuser_finance_view', name='superuser_finance_view'),
    url(r'^superuser/finance/delete$', 'superuser_finance_delete', name='superuser_finance_delete'),
    
    #STAFF SECTION
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^staff/(?P<group_id>\d+)/files/(?P<folder_id>\d+)/$', 'staff_group_files', name='staff_group_files'), 
    url(r'^staff/(?P<group_id>\d+)/checklist/$', 'staff_checklist_redirect', name='staff_checklist_redirect'),
    url(r'^staff/(?P<group_id>\d+)/checklist/(?P<year>\d+)/$', 'staff_checklist'),
    
    #ACCOUNT SECTION
    url(r'^account/profile/$', 'account_profile', name='account_profile'),
    url(r'^account/profile/edit/$', 'account_edit', name='account_edit'),
    url(r'^account/profile/delete/$', 'account_delete', name='account_delete'),
    url(r'^account/settings/$', 'account_settings', name='account_settings'),
    url(r'^account/files/(?P<folder_id>\d+)/$', 'account_files'),
    url(r'^account/checklist/$', 'account_checklist_redirect', name='account_checklist_redirect'),
    url(r'^account/checklist/(?P<year>\d+)/$', 'account_checklist'),
    url(r'^account/finance_request/$', 'account_finance_request',name="account_finance_request"),
    url(r'^account/finance_request/create/$', 'account_finance_request_create',name="account_finance_request_create"),
    
    #AJAX SECTIONS
    url(r'^ajax_delete_folder/$','ajax_delete_folder'),
    url(r'^ajax_delete_file/$','ajax_delete_file'),
    
    # url(r'^GCP/', include('GCP.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

gcpapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.db.models.signals import post_save
from django.forms import ModelForm
from django.forms.models import modelformset_factory

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    group_name = models.CharField(max_length=70,null=True)
    officer_name = models.CharField(max_length=50,null=True)
    academic_start_year = models.IntegerField(null=True)
    base_folder = models.ForeignKey("Folder",null=True)
    delete_me = models.BooleanField(default=False)
    group_description = models.TextField()

    #if user is an admin
    my_groups = models.ManyToManyField(User,related_name="my_groups_set")

    def delete(self, *args, **kwargs):
        self.base_folder.delete()
        super(UserProfile, self).delete(*args, **kwargs)

class UserForm(forms.Form):
    username = forms.CharField(max_length=30)
    group_name = forms.CharField(max_length=70)
    group_description = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    officer_name = forms.CharField(max_length=50, label="Sustainability Officer Name")
    academic_start_year = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput , label="Password")
    password_again = forms.CharField( widget=forms.PasswordInput, label="Password (again)" )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput , label="Password")

def content_file_name(instance, filename):
    return '/'.join(['users', instance.user.username,filename])

class Folder(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    parent = models.ForeignKey("Folder",related_name="folder_parent",null=True)
    sub_folders = models.ManyToManyField("Folder",related_name="sub")
    files = models.ManyToManyField("File")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def delete(self, *args, **kwargs):
        for file in self.files.all():
            file.delete()
        for folder in self.sub_folders.all():
            folder.delete()
        super(Folder, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.name

class File(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    file = models.FileField(upload_to=content_file_name)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return self.name
    def delete(self, *args, **kwargs):
        self.file.delete()
        super(File, self).delete(*args, **kwargs)

class Image(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True,blank=True)
    section = models.CharField(max_length=50,null=True)
    image = models.ImageField(upload_to="images")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return self.name
    def delete(self, *args, **kwargs):
        self.image.delete()
        super(Image, self).delete(*args, **kwargs)

class AcademicYear(models.Model):
    year = models.IntegerField(unique=True)
    def __unicode__(self):
        return str(self.year)

class QuestionBase(models.Model):
    question_text = models.TextField()
    point_value = models.IntegerField()
    
    def delete(self, *args, **kwargs):
        for question in self.question_base.all():
            question.delete()
        super(QuestionBase, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.question_text

class Question(models.Model):
    #AcademicYear.objects.filter(year=2012).aggregate(Sum('year'))
    user = models.ForeignKey(User)
    admin_comment = models.TextField(default="",blank=True)
    question_base = models.ForeignKey(QuestionBase,related_name="question_base")
    academic_year = models.ForeignKey(AcademicYear)
    question_text = models.TextField(null=True)
    description = models.TextField(default="",blank=True)
    files = models.ManyToManyField("File")
    is_approved = models.BooleanField(default=False)
    point_value = models.IntegerField(null=True)
    def delete(self, *args, **kwargs):
        for file in self.files.all():
            file.delete()
        super(Question, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.question_base.question_text

class QuestionGroup(models.Model):
    title = models.CharField(max_length=100)
    question_bases = models.ManyToManyField("QuestionBase")
    def delete(self, *args, **kwargs):
        for question in self.question_bases.all():
            question.delete()
        super(QuestionGroup, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.title
        
class Checklist(models.Model):
    user = models.ForeignKey(User)
    questions = models.ManyToManyField("Question")
    academic_year = models.ForeignKey("AcademicYear")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return str(self.user) + "-" + str(self.academic_year.year)

class Announcement(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    body = models.TextField(default="", blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    #images = models.ManyToManyField("Image")
    entry = models.CharField(max_length=50)
    def __unicode__(self):
        return self.title

class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        exclude = ('entry','timestamp')

AnnouncementFormSet = modelformset_factory(Announcement, max_num=0, exclude=('entry',))

class FinanceRequest(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField(default="",blank=True)
    reimburse_name = models.CharField(max_length=40)
    student_id_or_group_num = models.CharField(max_length=40)
    address = models.TextField(default="",blank=True)
    is_approved = models.BooleanField(default=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receipt_file = models.OneToOneField("File",null=True)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    is_answered = models.BooleanField(default=False) #whether or not an admin responded
    admin_deleted = models.BooleanField(default=False)
    user_deleted = models.BooleanField(default=False)
    
    def delete(self, *args, **kwargs):
        self.receipt_file.delete()
        super(FinanceRequest, self).delete(*args, **kwargs)
    def __unicode__(self):
        return str(self.user.username) + " - $%d" % self.amount

class FinanceRequestForm(ModelForm):
    description = forms.CharField(label="Which point will this help you complete?",widget=forms.Textarea)
    reimburse_name = forms.CharField(label="Who should we reimburse?")
    student_id_or_group_num = forms.CharField(label="Student ID or Group Account #")
    address = forms.CharField(label="Address (if student group, please use ASUC Address)",widget=forms.Textarea)
    class Meta:
        model = FinanceRequest
        exclude = ('user','is_approved','is_answered','admin_deleted','user_deleted','receipt_file') #implicit fields
        fields = ('amount','description','reimburse_name','student_id_or_group_num','address') #specifies order


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        folder = Folder.objects.create(user=instance,name='Base')
        finance = Folder.objects.create(user=instance,name='Finance',parent=folder)
        pictures = Folder.objects.create(user=instance,name='Pictures',parent=folder)
        miscellaneous = Folder.objects.create(user=instance,name='Miscellaneous',parent=folder)
        reports = Folder.objects.create(user=instance,name='Reports',parent=folder)
        folder.sub_folders.add(finance)
        folder.sub_folders.add(pictures)
        folder.sub_folders.add(miscellaneous)
        folder.sub_folders.add(reports)
        profile = UserProfile.objects.create(user=instance,base_folder=folder)
        if instance.is_superuser:
            for user in User.objects.filter(is_staff=False):
                profile.my_groups.add(user)


post_save.connect(create_user_profile, sender=User)

GCP/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block content %}


    <div class="span12">
            <legend class="header"><h2> About </h2></legend>
            <p>
               The ASUC Green Certification Program was first 
               conceptualized in the Fall of 2009 by Vanessa 
               Fernandez and Elliot Goldstein. Via networking 
               and advisement by the Office of Sustainability 
               during the fall the program was able to conduct a 
               pilot program during the spring of 2011 with six 
               different student groups on campus. Vanessa and Elliot
               concurrently worked on a grant and submitted the pilot
               program's findings to TGIF that spring, receiving $31,500
               in funding for a two year beta program. </p>
    <hr>
	<h2 class="about-head">How It Works</h2>
	<p>
    The ASUC GCP has two components, auditing and certification. 
    Each component of the program follows our Checklist in order to ensure 
    that groups are striving to reduce their overall waste in seven different 
    categories: Waste Management, Advertising & Paper Reduction, Publications, 
    Transportation, Food & Dining, Events, Miscellaneous. A copy of the Checklist 
    can be found in the resources section of our page. After completely a general 
    requirement of at least 20 points, a group will likely be certified. 
	<br>
	Upon certification groups receive 10% additional funding the following year among other benefits. 
	</p>
    <hr>
    
	<h2 class="about-head">Auditing</h2>
<p>    
Initially, an email announcing application dates and an attached application form are sent out 
to student groups via the ASUC listserv. Applications received are reviewed and the selected groups 
are emailed an invitation into the program.
<ul>
    <li>    
    Phase One
    <ul>
        <li>
        Selected groups attend the initial meeting with an assigned Green Certification Auditor. 
        The lecture includes explanations on the program structure, funding model and an initial assessment (goals, etc.).
        </li><li>
        Groups attend weekly meetings for the first month to ensure proper acclamation to the program's structure. 
        Each group then sets up monthly meetings with their GreenCATs.
        </li>
    </ul>
    </li>
    <li>Phase Two
    <ul>
        <li>
        A midterm assessment of each group's progress is turned in during February. 
        At this point, each auditor will give a brief presentation on his/her group and discuss any 
        successes or hardships experienced by the groups.
        </li><li>
        Auditors then develop a new game plan to help each group become a Certified Green Group by April.
        </li>
    </ul>
    </li>
    <li>
    Phase Three
    <ul>
        <li>
        In the final auditing meeting, GreenCATs give their final presentation on the newly certified 
        or denied groups. We then discuss reasons for their certification and reasons that some groups 
        were not certified. An email is then sent to certified groups, announcing their certification.
        </li>
    </ul>
    </li>
</ul>
</p>

    <hr>
    <h2 class="about-head">Certification </h2>
        <p>Once groups are certified our GreenCATs will be assigned to them annually and maintain contact monthly 
        to ensure groups continue to strive towards sustainable causes. Our role here is really to ensure that any questions 
        groups have are answered and any sustainable endeavors are supported to the best of our ability. Groups are recertified 
        annually and a final report is released regarding their process. 
    </p>
    </div>

{% endblock %}

{% block post_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#about-nav").addClass("active")
  })
</script>
{% endblock %}

GCP/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="description" content="ASUC Green Certification Program at UC Berkeley." />
    <meta name="keywords" content="UC Berkeley, UCB, ASUC Green Certification Program, Green Cat" /> 
    {% block top_head %} {% endblock %}
    <title>
        {% block title %}
            Home
        {% endblock %}
    </title>
    
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/static/style.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,200,400,500,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oregano' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" href="/static/favicon.ico">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <style type="text/css">
        {% block css %}
        {% endblock %}
    </style>

    {% block head %}
    {% endblock %}


</head>
<body>
{% block body %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endblock %}
<div id="whole-container">

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse">
                
                <a class="brand" href="/">
                    GCP
                </a>
                <ul class="nav">
                    <li id="home-nav"><a href="/"> Home </a></li>
                    <li id="about-nav"><a href="{% url about %}"> About </a></li>
                    <li id="green_groups-nav"><a href="{% url green_groups %}"> Green Groups </a></li>
                    <li id="resources-nav"><a href="{% url resources %}"> Resources </a></li>
                    <li id="reports-nav"><a href="{% url reports %}"> GCP Reports </a></li>
                    <li id="contact-nav"><a href="{% url contact %}"> Contact </a></li>
                </ul>
                <ul class="nav pull-right">
                    {% if user.is_superuser %}
                        <li id="superuser-nav"><a href="{% url superuser %}"> Super User </a></li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li id="staff-nav"><a href="{% url staff %}"> Staff </a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li id="account-nav"><a href="{% url account_profile %}"><i class="icon-cog"></i> Account</a></li>
                        <li><a href="/logout/" style="margin-left: 5px; font-weight: bold;"> Log out </a></li>
                    {% else %}
                        <div class="btn-group">
                            <a href="{% url login %}" class="btn"> Log In </a>
                            <a href="{% url signup %}" class="btn btn-success"> Sign Up</a>
                        </div>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="inner-body">
{% block all_content %}
<div class="container page-content">

{% block content %}
{% endblock %}

</div> <!-- End container -->
{% endblock %}
</div>


<div class="footer">
    <div class="container">
        <div class="span2">
            <img src="/static/images/Berkeley_Seal.png" style="height:70px; width:70px;" alt="">
        </div>
        <div class="span6">
            <img src="/static/images/logo-black_text.png" style="height:58px; width:409px;" alt="">
        </div>
        <div class="span2">
            <img src="/static/images/ASUC-Green-Cert-Logos-2.png" style="height:70px; width:78px;" alt="">
        </div>
        <div class="fb-like" data-href="https://www.facebook.com/ASUCgreencert" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true" data-font="verdana"></div>
        
    </div>
</div>


<script src="/static/javascript.js"></script>
<script src="/static/bootstrap/js/bootstrap.js"></script>
{% block post_js %}
{% endblock %}

</div> <!-- end #whole-container -->
</body>
</html>

GCP/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class="span12">
            <legend class="header"><h2> Contact Us</h2></legend>
            <p>
                Feel free to contact us through the following means.<br><Br>
                Email: <a href="mailto:asucgreencat@gmail.com">asucgreencat@gmail.com</a><br>
                Visit our <a href = "https://www.facebook.com/ASUCgreencert">Facebook</a> or like us down below!<br>
                <div class="fb-like-box" data-href="http://www.facebook.com/asucgreencert" data-width="300" data-height="350" data-show-faces="true" data-stream="false" data-header="true"></div>
            </p>
    </div>

{% endblock %}

{% block post_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#contact-nav").addClass("active")
  })
</script>
{% endblock %}

GCP/templates/green_groups.html
{% extends "base.html" %}

{% block title %}Green Groups{% endblock %}

{% block content %}


    <div class="span12">
            <legend class="header"><h2> Green Groups </h2></legend>
            
            {% if verified_users %}
            <p> Here are our green groups! Click on them to see their description.</p>

            <div class="accordion" id="accordion2">
                {% for user in verified_users %}
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-{{user.id}}">
                      {{ user.get_profile.group_name }}
                    </a>
                  </div>
                  <div id="collapse-{{ user.id}}" class="accordion-body collapse">
                    <div class="accordion-inner">
                       <p style="white-space: pre-wrap">{{ user.get_profile.group_description }}</p>
                    </div>
                  </div>
                </div>
                {% endfor %}
                
            </div>
            {% else %}
            <p style="font-size:20px;">Sorry, no green groups exist yet!</p>
            {% endif %}
    </div>

{% endblock %}

{% block post_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#green_groups-nav").addClass("active")
  })
</script>
{% endblock %}

GCP/templates/home.html
{% extends "base.html" %}
{% block css %}
body {
    background-color: white;
    background-image: none;
}
.container {
    /* width: auto; */
    min-width: 960px;
}
{% endblock %}


{% block all_content %}
<div class="page-content">

<div id="index-banner">
    <div id="index-internal">
        <div class="" style="float: left;">
            <img src="/static/images/ASUC-Green-Cert-Logos-1.png" alt="">
        </div>
        <div class="index-slogan" style="float: left; padding-left:20px;">
            <h1 style="letter-spacing:-1px;color: #026440;
font-family: 'Trebuchet MS', Helvetica, sans-serif;text-shadow:0 0 0.2em white;">ASUC Green Certification Program<br>
                <h2 >Sustainability for the future</h2>
            </h1>
        </div>
    </div>
    
    <br clear="both" />
</div>
{% block content %}
    <!--
    <div >
    <img class="center" src="static/powersave.jpg" style="padding-left: 0px; width:980px; height: 175px;" >
    </div>
    -->
    <div class="page-content">
        <div class="middle-container">
            <div class="middle-banner" >
              <div id="home-announcement">
                <h2 style="font-family: 'Proxima Nova', 'proxima-nova', 'Helvetica Neue', Helvetica, sans-serif; text-align:center; letter-spacing: -1px; border-bottom: 1px solid black; font-size:22px; margin-bottom:15px; line-height:1.2;"> {{ top.title }} </h2>
                <p style="white-space: pre-wrap;">{{ top.body }}</p>    
              </div>
              
              <div id="myCarousel" class="carousel slide set-image-dimension" style="float:left; margin-bottom: 0;">
                <div class="carousel-inner">
                    
                    {% for image in images %}
                
                    {% if forloop.first %}
                        <div class="active item">
                    {% else %}
                        <div class="item">
                    {% endif %}
                    <img class="set-image-dimension" src="{{ image.image.url }}" alt="...">
                    
                    {% if image.description %}
                    <div class="carousel-caption">
                      <p style="white-space: pre-wrap"> {{ image.description }} </p>
                    </div>
                    {% endif %}
                    
                    </div>
                    
                    {% endfor %}
                    
                </div>
                
                {% if images|length > 1 %}
                <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                {% endif %}
              </div>
            
              
            </div>
            <br clear="both" />
         </div>
            
            
            
            <div class="lower-banner">
              <div class="lower-container">
                <h1 style="text-align:center;"> Announcements </h1><br>
            
                <div class="shadow-text-box">
                  <div class="text-head">
                    {{ bottom_left.title }}
                  </div>
                  <div class="text-body">
                    <p style="white-space: pre-wrap;">{{ bottom_left.body }}</p>
                  </div>
                </div>
                
                <div class="shadow-text-box">
                  <div class="text-head">
                    {{ bottom_mid.title }}
                  </div>
                  <div class="text-body">
                    <p style="white-space: pre-wrap;">{{ bottom_mid.body }}</p>
                  </div>
                </div>
                
                <div class="shadow-text-box">
                  <div class="text-head">
                    {{ bottom_right.title }}
                  </div>
                  <div class="text-body">
                    <p style="white-space: pre-wrap;">{{ bottom_right.body }}</p>
                  </div>
                </div>
            
                <div style="float:right; background-color: white;" class="fb-like-box" data-href="http://www.facebook.com/asucgreencert" data-width="200" data-height="300" data-show-faces="true" data-stream="true" data-header="true"></div>
              </div>
              <br clear="both" />
            </div>       
            
            
    </div>
    <br clear="both" />


{% endblock %}
</div>
{% endblock %}

{% block post_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#home-nav").addClass("active")
    $('.carousel').carousel({
        pause: "hover"
    })
  })
</script>
{% endblock %}

GCP/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block all_content %}
<div class="page-stretch">

<center>
<div class="container well" style="background-color: white; width:400px;">


        <h2 style="text-align:center"> Sign In</h2>
        <br>
        <form action="."  method="post" class="form-horizontal" id="login-form">{% csrf_token %}
        <div id="fields form">
    {% for field in form %}
      <div class="control-group">
        <label for="name" class="control-label small-label"  id="{{field.html_name}}">{{ field.label }}</label>
        <div class="controls small-controls">
        {{ field }}
          <span class="help-block">{{ field.help_text }}</span>
        </div>
      </div>
    {% endfor %}
  </div>
  {% if fail %}
  <p style="text-align:center; color:red;"> Your username or password is incorrect. Please try again. </p>
  {% endif %}
  
  <input type="submit" class="btn btn-primary btn-large" style="width:250px" value="Login" />
  
</div>

</div>

</center>

{% endblock %}

GCP/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block top_head %}
<style type='text/css'>
label.error {
 float: none;
 color: red;
 padding-left: 30px;
 vertical-align: top;
 }
 </style>
{% endblock %}

{% block content %}

<div class="span12">
<legend class="header">
    <h2> Create an account</h2>
  </legend>
<form action="."  method="post" class="form-horizontal" id="sellForm">{% csrf_token %}
  

  <br />
  <div id="fields form">
    {% for field in form %}
      <div class="control-group">
        {{ field.errors }}
        <label class="control-label signup-label" id="{{field.html_name}}">{{ field.label }}</label>
        <div class="controls ">
        {{ field }}
          <span class="help-block">{{ field.help_text }}</span>
        </div>
      </div>
    {% endfor %}
  </div>
  <br />
  <input type="submit" style="margin-left:190px" class="btn btn-primary" value="Send Application" />

  </form>
  </div>

{% endblock %}

{% block post_js %}
<script type="text/javascript" src="/static/jquery-validation-1.9.0/jquery.validate.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#id_group_description").css("width","600px");

    $("#sellForm").validate({
      rules: {
        email: {
          required: true,
          email: true,
        },
        group_name: {
          required: true,
          maxlength: 70
        },
        group_description: {
          required: true,
        },
        username: {
          required: true,
          maxlength: 30
        },
        officer_name: {
          required: true,
          maxlength: 50
        },
        academic_start_year: {
          required: true,
          number: true,
          min: 1950,
          max: 2050,
        },
        password: {
          required: true,
          minlength: 6,
          maxlength: 22,
        },
        password_again: {
          required: true,
          equalTo: "#id_password"
        },
      } 
    });
    

});
</script>
{% endblock %}

GCP/templates/small_message.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block all_content %}
    <div class="page-stretch">
    <div class="well container" style="background-color: white; width: 450px; ">
        <legend ><h2> {{ title }}</h2></legend>
        <p> 
            {{ message }}
            <br><br>
            <a href="/">Click here to go home.</a>
        </p>
    </div>
    </div>

{% endblock %}