GCP/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('gcpapp.views',

    url(r'^$', 'home', name='home'),
    url(r'^about/$', 'about', name='about'),
    url(r'^green_groups/$', 'green_groups', name='green_groups'),
    url(r'^resources/$', 'resources', name='resources'),
    url(r'^reports/$', 'reports', name='reports'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^signup/$', 'signup', name='signup'),
    url(r'^accounts/login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    
    #SUPERUSER SECTION
    url(r'^superuser/$', 'superuser_content', name='superuser'),
    url(r'^superuser/verify/$', 'superuser_verify', name='superuser_verify'),
    url(r'^superuser/academic_year/$', 'superuser_academic_year', name='superuser_academic_year'),
    url(r'^superuser/questions/$', 'superuser_questions', name='superuser_questions'),
    url(r'^superuser/questions/edit/$', 'superuser_questions_edit'),
    url(r'^superuser/staff/$', 'superuser_staff', name='superuser_staff'),
    url(r'^superuser/staff/(?P<user_id>\d+)/$', 'superuser_staff_user', name='superuser_staff_user'),
    url(r'^superuser/staff/create/$', 'superuser_staff_create', name='superuser_staff_create'),
    url(r'^superuser/all_accounts/$', 'superuser_all_accounts', name='superuser_all_accounts'),
    url(r'^superuser/finance/$', 'superuser_finance', name='superuser_finance'),
    url(r'^superuser/finance/(?P<finance_id>\d+)/$', 'superuser_finance_view', name='superuser_finance_view'),
    url(r'^superuser/finance/delete$', 'superuser_finance_delete', name='superuser_finance_delete'),
    
    #STAFF SECTION
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^staff/(?P<group_id>\d+)/files/(?P<folder_id>\d+)/$', 'staff_group_files', name='staff_group_files'), 
    url(r'^staff/(?P<group_id>\d+)/checklist/$', 'staff_checklist_redirect', name='staff_checklist_redirect'),
    url(r'^staff/(?P<group_id>\d+)/checklist/(?P<year>\d+)/$', 'staff_checklist'),
    
    #ACCOUNT SECTION
    url(r'^account/profile/$', 'account_profile', name='account_profile'),
    url(r'^account/profile/edit/$', 'account_edit', name='account_edit'),
    url(r'^account/profile/delete/$', 'account_delete', name='account_delete'),
    url(r'^account/settings/$', 'account_settings', name='account_settings'),
    url(r'^account/files/(?P<folder_id>\d+)/$', 'account_files'),
    url(r'^account/checklist/$', 'account_checklist_redirect', name='account_checklist_redirect'),
    url(r'^account/checklist/(?P<year>\d+)/$', 'account_checklist'),
    url(r'^account/finance_request/$', 'account_finance_request',name="account_finance_request"),
    url(r'^account/finance_request/create/$', 'account_finance_request_create',name="account_finance_request_create"),
    
    #AJAX SECTIONS
    url(r'^ajax_delete_folder/$','ajax_delete_folder'),
    url(r'^ajax_delete_file/$','ajax_delete_file'),
    
    # url(r'^GCP/', include('GCP.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

gcpapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.db.models.signals import post_save
from django.forms import ModelForm
from django.forms.models import modelformset_factory

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    group_name = models.CharField(max_length=70,null=True)
    officer_name = models.CharField(max_length=50,null=True)
    academic_start_year = models.IntegerField(null=True)
    base_folder = models.ForeignKey("Folder",null=True)
    delete_me = models.BooleanField(default=False)
    group_description = models.TextField()

    #if user is an admin
    my_groups = models.ManyToManyField(User,related_name="my_groups_set")

    def delete(self, *args, **kwargs):
        self.base_folder.delete()
        super(UserProfile, self).delete(*args, **kwargs)

class UserForm(forms.Form):
    username = forms.CharField(max_length=30)
    group_name = forms.CharField(max_length=70)
    group_description = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    officer_name = forms.CharField(max_length=50, label="Sustainability Officer Name")
    academic_start_year = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput , label="Password")
    password_again = forms.CharField( widget=forms.PasswordInput, label="Password (again)" )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput , label="Password")

def content_file_name(instance, filename):
    return '/'.join(['users', instance.user.username,filename])

class Folder(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    parent = models.ForeignKey("Folder",related_name="folder_parent",null=True)
    sub_folders = models.ManyToManyField("Folder",related_name="sub")
    files = models.ManyToManyField("File")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def delete(self, *args, **kwargs):
        for file in self.files.all():
            file.delete()
        for folder in self.sub_folders.all():
            folder.delete()
        super(Folder, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.name

class File(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    file = models.FileField(upload_to=content_file_name)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return self.name
    def delete(self, *args, **kwargs):
        self.file.delete()
        super(File, self).delete(*args, **kwargs)

class Image(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True,blank=True)
    section = models.CharField(max_length=50,null=True)
    image = models.ImageField(upload_to="images")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return self.name
    def delete(self, *args, **kwargs):
        self.image.delete()
        super(Image, self).delete(*args, **kwargs)

class AcademicYear(models.Model):
    year = models.IntegerField(unique=True)
    def __unicode__(self):
        return str(self.year)

class QuestionBase(models.Model):
    question_text = models.TextField()
    point_value = models.IntegerField()
    
    def delete(self, *args, **kwargs):
        for question in self.question_base.all():
            question.delete()
        super(QuestionBase, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.question_text

class Question(models.Model):
    #AcademicYear.objects.filter(year=2012).aggregate(Sum('year'))
    user = models.ForeignKey(User)
    admin_comment = models.TextField(default="",blank=True)
    question_base = models.ForeignKey(QuestionBase,related_name="question_base")
    academic_year = models.ForeignKey(AcademicYear)
    question_text = models.TextField(null=True)
    description = models.TextField(default="",blank=True)
    files = models.ManyToManyField("File")
    is_approved = models.BooleanField(default=False)
    point_value = models.IntegerField(null=True)
    def delete(self, *args, **kwargs):
        for file in self.files.all():
            file.delete()
        super(Question, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.question_base.question_text

class QuestionGroup(models.Model):
    title = models.CharField(max_length=100)
    question_bases = models.ManyToManyField("QuestionBase")
    def delete(self, *args, **kwargs):
        for question in self.question_bases.all():
            question.delete()
        super(QuestionGroup, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.title
        
class Checklist(models.Model):
    user = models.ForeignKey(User)
    questions = models.ManyToManyField("Question")
    academic_year = models.ForeignKey("AcademicYear")
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    def __unicode__(self):
        return str(self.user) + "-" + str(self.academic_year.year)

class Announcement(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    body = models.TextField(default="", blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    #images = models.ManyToManyField("Image")
    entry = models.CharField(max_length=50)
    def __unicode__(self):
        return self.title

class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        exclude = ('entry','timestamp')

AnnouncementFormSet = modelformset_factory(Announcement, max_num=0, exclude=('entry',))

class FinanceRequest(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField(default="",blank=True)
    reimburse_name = models.CharField(max_length=40)
    student_id_or_group_num = models.CharField(max_length=40)
    address = models.TextField(default="",blank=True)
    is_approved = models.BooleanField(default=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    receipt_file = models.OneToOneField("File",null=True)
    timestamp = models.DateTimeField(auto_now_add=True,null=True)
    is_answered = models.BooleanField(default=False) #whether or not an admin responded
    admin_deleted = models.BooleanField(default=False)
    user_deleted = models.BooleanField(default=False)
    
    def delete(self, *args, **kwargs):
        self.receipt_file.delete()
        super(FinanceRequest, self).delete(*args, **kwargs)
    def __unicode__(self):
        return str(self.user.username) + " - $%d" % self.amount

class FinanceRequestForm(ModelForm):
    description = forms.CharField(label="Which point will this help you complete?",widget=forms.Textarea)
    reimburse_name = forms.CharField(label="Who should we reimburse?")
    student_id_or_group_num = forms.CharField(label="Student ID or Group Account #")
    address = forms.CharField(label="Address (if student group, please use ASUC Address)",widget=forms.Textarea)
    class Meta:
        model = FinanceRequest
        exclude = ('user','is_approved','is_answered','admin_deleted','user_deleted','receipt_file') #implicit fields
        fields = ('amount','description','reimburse_name','student_id_or_group_num','address') #specifies order


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        folder = Folder.objects.create(user=instance,name='Base')
        finance = Folder.objects.create(user=instance,name='Finance',parent=folder)
        pictures = Folder.objects.create(user=instance,name='Pictures',parent=folder)
        miscellaneous = Folder.objects.create(user=instance,name='Miscellaneous',parent=folder)
        reports = Folder.objects.create(user=instance,name='Reports',parent=folder)
        folder.sub_folders.add(finance)
        folder.sub_folders.add(pictures)
        folder.sub_folders.add(miscellaneous)
        folder.sub_folders.add(reports)
        profile = UserProfile.objects.create(user=instance,base_folder=folder)
        if instance.is_superuser:
            for user in User.objects.filter(is_staff=False):
                profile.my_groups.add(user)


post_save.connect(create_user_profile, sender=User)

GCP/templates/superuser/OLD_superuser_finance - Copy.html
{% extends "superuser/superuser.html" %}

{% block title %} Admin - Finance{% endblock %}

{% block super_content %}
    {% if message %}
    <p style="color:red">{{ message }}</p>
    {% endif %}
    <form method="post" action="."> {% csrf_token %}
    <table class="table table-bordered">
        <caption><h2> Finance Requests </h2></caption>
        <thead>
            <tr>
                <th> Group </th>
                <th> Officer Name </th>
                <th> Email </th>
                <th> Amount </th>           
            </tr>
        </thead>
        <tbody>
            {% for finance in finance_requests %}
            <tr>
                <td> 
                    <input style="margin-top: -3px;" type="radio" name="approve" value="{{ finance.id }}"> Approve<br>
                    <input style="margin-top: -3px;" type="radio" name="decline" value="{{ finance.id }}"> Decline
                </td>
                <td> {{ finance.user.get_profile.group_name}} </td>
                <td> {{ finance.user.get_profile.officer_name }} </td>
                <td> {{ finance.user.email }} </td>
                <td> {{ finance.title }} </td>
                <td> <a href="#modal-{{finance.id}}" class="btn btn-info" data-toggle="modal">View </a> </td>
                <td> ${{ finance.value }} </td>

            </tr>
            
            <div class="modal hide fade" id="modal-{{finance.id}}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon icon-remove"></i></button>
                    <h2 id="modal-{{finance.id}}-label">{{finance.title}} </h2>
                </div>
                <div class="modal-body">
                    <p style="white-space: pre-wrap">{{ finance.description }}</p>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
    
    <input class="btn btn-success" type="submit" value="Respond" /> 
    </form>
    
    
    <form method="post" action="./delete"> {% csrf_token %}
    <table class="table table-bordered">
        <caption><h2> Old Finance Requests </h2></caption>
        <thead>
            <tr>
                <th> Status </th>
                <th> Group </th>
                <th> Officer Name </th>
                <th> Email </th>
                <th> Title </th>
                <th style="width: 70px;"> Description </th>
                <th> Amount </th>
                <th> Delete </th>
            </tr>
        </thead>
        <tbody>
            {% for finance in old_requests %}
            <tr>
                <td> 
                    {% if finance.is_approved %}
                    <span style="color: green"> Approved </span>
                    {% else %}
                    <span style="color: red"> Declined </span>
                    {% endif %}
                </td>
                <td> {{ finance.user.get_profile.group_name}} </td>
                <td> {{ finance.user.get_profile.officer_name }} </td>
                <td> {{ finance.user.email }} </td>
                <td> {{ finance.title }} </td>
                <td> <a href="#modal-{{finance.id}}" class="btn btn-info" data-toggle="modal">View </a> </td>
                <td> ${{ finance.value }} </td>
                <td>
                  <input style="margin-top:0px;" type="checkbox" name="Delete" value="{{ finance.id }}"> Delete
                </td>

            </tr>
            
            <div class="modal hide fade" id="modal-{{finance.id}}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon icon-remove"></i></button>
                    <h2 id="modal-{{finance.id}}-label">{{finance.title}} </h2>
                </div>
                <div class="modal-body">
                    <p style="white-space: pre-wrap">{{ finance.description }}</p>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
    <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
{% endblock %}

{% block super_js %}
    <script type="text/javascript">
        $(document).ready( function() {
            $("#pill-finance").addClass("active");
            
        })
    </script>

{% endblock %}

GCP/templates/superuser/superuser.html
{% extends "base.html" %}

{% block content %}


    <div class="span12">
        <br>
        <ul class="nav nav-pills" style="margin-bottom: 0px">
            <li id="pill-home">
            <a href="{% url superuser %}">General</a>
            </li>
            <li id="pill-verify"><a href="{% url superuser_verify %}">Verify Accounts</a></li>
            <li id="pill-academic-year"><a href="{% url superuser_academic_year %}">Academic Year</a></li>
            <li id="pill-questions"><a href="{% url superuser_questions %}">Checklist Questions</a></li>
            <li id="pill-finance"><a href="{% url superuser_finance %}">Finance Requests</a></li>
            <li id="pill-staff"><a href="{% url superuser_staff %}">Staff</a></li>
            <li id="pill-all-accounts"><a href="{% url superuser_all_accounts %}">All Accounts</a></li>
        </ul>
        <div class="empty-padding"> </div>
        {% block super_content %}
        {% endblock %}
    </div>

{% endblock %}

{% block post_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#superuser-nav").addClass("active")
  })
</script>
{% block super_js %}{% endblock %}
{% endblock %}

GCP/templates/superuser/superuser_academic_year.html
{% extends "superuser/superuser.html" %}

{% block title %} Admin - Academic Year{% endblock %}

{% block super_content %}
    {% if message %}
    <p style="color:red">{{ message }}</p>
    {% endif %}

    <table class="table table-bordered">
        <thead>
        <tr>
            <th> Academic Year</th>
            <th> Delete </th>
        </tr>
        </thead>
        <tbody>
        {% for year in years %}
            <form action="." method="post" id="yearForm" onsubmit="return confirm('You\'re going to lose all data associated with this year, are you sure you want to proceed?')">{% csrf_token %}
            <input type="hidden" name="delete_year" value="{{ year.id }}" />

            <tr>
                <td> {{year.year}}</td>
                <td>
                    <input type="submit" class="btn btn-danger btn-small" value='Delete' />

                </td>
            </tr>

            </form>
        {% endfor %}
        </tbody>
    </table>

    <br>
    <form action="." method="post" id="yearForm">{% csrf_token %}
    <h4>Add New Year</h4>
    <p><span style="padding-right:10px;">Year</span> <input type="text" name="new_year" /></p>
    <input type="submit" class="btn btn-primary" type="button" value="Submit" />
    </form>
    
    <br>
    <h4> Note </h4>
    <p>
        For each year that exists, users will have a questionnaire they can fill out.<br>
        Make sure not to have any unnecessary years and be EXTREMELY careful when you delete a year as all user data from that year will be lost.<br>
        Also, note that the active year will be the current greatest year.<br><br>
    </p>
{% endblock %}

{% block super_js %}
    <script type="text/javascript" src="/static/jquery-validation-1.9.0/jquery.validate.min.js"></script>
    <script type="text/javascript">
        $(document).ready( function() {
            $("#pill-academic-year").addClass("active");
            $("#yearForm").validate({
                rules: {
                    new_year: {
                        required: true,
                        number:true
                    }
                }
            })
        })
    </script>

{% endblock %}

GCP/templates/superuser/superuser_all_accounts.html
{% extends "superuser/superuser.html" %}

{% block title %} Admin - All Accounts{% endblock %}

{% block super_content %}
    {% if message %}
    <p style="color:red">{{ message }}</p>
    {% endif %}
    
    <form id="delete_form" action="." onsubmit="return confirmMessage()" method="post">
    {% csrf_token %}
    <table class="table table-bordered">
                <caption><h2>All Groups</h2></caption>
                <thead>
                  <tr>
                    <th style="width: 70px;"> Delete </th>
                    <th> Username </th>
                    <th> Group Name </th>
                    <th> Email</th>
                    <th> Officer Name</th>
                    <th> Start Year</th>
                    <th style="width: 140px;"> Group Description </th>
                  </tr>
                </thead>
                <tbody>
                {% for user in all_groups %}
                  <tr>
                    <td><input style="margin-top:0px;" type="checkbox" name="Delete" value="{{ user.id }}"> Delete</td>
                    <td> {{user.username}}</td>
                    <td> {{user.get_profile.group_name}}</td>
                    <td> {{user.email}}</td>
                    <td> {{user.get_profile.officer_name}}</td>
                    <td> {{user.get_profile.academic_start_year}}</td>
                    <td> <a href="#modal-{{user.id}}" class="btn btn-info" data-toggle="modal">View Description</a></td>
 
                  </tr>
                  
                    <div class="modal hide fade" id="modal-{{user.id}}">
                        <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon icon-remove"></i></button>
                        <h2 id="modal-{{user.id}}-label">{{user.get_profile.group_name}} </h2>
                        </div>
                        <div class="modal-body">
                        <p style="white-space: pre-wrap">{{ user.get_profile.group_description }}</p>
                        </div>
                        <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                        </div>
                    </div>
                {% endfor %}
                </tbody>
            </table>
    
    <table class="table table-bordered">
        <caption><h2>All Staff and Super Users </h2></caption>
        <thead>
            <tr>
                <th style="width: 70px;"> Delete </th>
                <th> Username </th>
                <th> First Name </th>
                <th> Last Name </th>
                <th> Email</th>
                <th> Account Type </th>
            </tr>
        </thead>
        <tbody>
            {% for entry in all_staff %}
            <tr>
                <td>
                    <input style="margin-top:0px;" type="checkbox" name="Delete" value="{{ entry.id }}" {% if entry.is_superuser %}class="superuser"{%endif%}> Delete
                </td>
                <td> {{ entry.username }} </td>
                <td> {{ entry.first_name }} </td>
                <td> {{ entry.last_name }} </td>
                <td> {{ entry.email }} </td>
                <td>
                {% if entry.is_superuser %} 
                Super User
                {% else %}
                Staff
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <input type="submit" value="Delete" class="btn btn-danger" />
    
    </form>
{% endblock %}

{% block super_js %}
    <script type="text/javascript">
        $(document).ready( function() {
            $("#pill-all-accounts").addClass("active");
            
        })
        
        function confirmMessage() {
            var n = $("#delete_form input:checked").length;
            if (n==0) {
                alert('You have not selected any accounts');
                return false;
            }
            
            //safeguard from deleting all superusers
            var selected_supers = $("input.superuser:checked").length;
            var all_supers = $("input.superuser").length;
            if (selected_supers === all_supers) {
                alert("You can't delete superusers to the point where you have none. You MUST have at least one existing.");
                return false;
            }
        
            var bool = confirm('Are you sure you want to delete these accounts? You are going to lose all user related data as well. This action is permanent.')
            return bool;
        }
    </script>

{% endblock %}

GCP/templates/superuser/superuser_finance.html
{% extends "superuser/superuser.html" %}

{% block title %} Admin - Finance{% endblock %}

{% block super_content %}
    {% if message %}
    <p style="color:red">{{ message }}</p>
    {% endif %}

    <table class="table table-bordered">
        <caption><h2> Finance Requests </h2></caption>
        <thead>
            <tr>
                <th> View/Action </th>
                <th> Group </th>
                <th> Officer Name </th>
                <th> Email </th>
                <th> Amount </th>
                <th> Submission Date </th>
            </tr>
        </thead>
        <tbody>
            {% for finance in finance_requests %}
            <tr>
                <td> <a href="./{{finance.id}}">View/Action </a> </td>
                <td> {{ finance.user.get_profile.group_name}} </td>
                <td> {{ finance.user.get_profile.officer_name }} </td>
                <td> {{ finance.user.email }} </td>
                <td> ${{ finance.amount }} </td>
                <td> {{ finance.timestamp }} </td>

            </tr>
            
            {% endfor %}
        </tbody>
    </table>

    <table class="table table-bordered">
        <caption><h2> Old Finance Requests </h2></caption>
        <thead>
            <tr>
                <th> View/Delete </th>
                <th> Group </th>
                <th> Officer Name </th>
                <th> Email </th>
                <th> Amount </th>
                <th> Submission Date </th>
                <th> Status </th>
            </tr>
        </thead>
        <tbody>
            {% for finance in old_requests %}                
            <tr>
                <td> <a href="./{{finance.id}}">View/Delete </a> </td>
                <td> {{ finance.user.get_profile.group_name}} </td>
                <td> {{ finance.user.get_profile.officer_name }} </td>
                <td> {{ finance.user.email }} </td>
                <td> ${{ finance.amount }} </td>
                <td> {{ finance.timestamp }} </td>
                <td> 
                    {% if finance.is_approved %}
                    <span style="color: green"> Approved </span>
                    {% else %}
                    <span style="color: red"> Declined </span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block super_js %}
    <script type="text/javascript">
        $(document).ready( function() {
            $("#pill-finance").addClass("active");
            
        })
    </script>

{% endblock %}

GCP/templates/superuser/superuser_home.html
{% extends "superuser/superuser.html" %}
{% block title %}Admin{% endblock %}
        {% block super_content %}
        <p>
            Please select from the top where you would like to administrate.
        </p>
        {% endblock %}

{% block super_js %}
<script type="text/javascript">
  $(document).ready( function() {
    $("#pill-home").addClass("active")
  })
</script>

{% endblock %}

GCP/templates/superuser/superuser_staff_create.html
{% extends "superuser/superuser.html" %}

{% block title %} Admin - Create Staff{% endblock %}

{% block top_head %}
<style type='text/css'>
label.error {
 float: none;
 color: red;
 padding-left: 30px;
 vertical-align: top;
 }
 </style>
{% endblock %}

{% block super_content %}
    {% if message %}
    <p style="color:red">{{ message }}</p>
    {% endif %}
    <div class="span12">
    <legend><h2> Create New Staff Member </h2></legend>
    <form action="."  method="post" class="form-horizontal" id="sellForm">
    {% csrf_token %}
  

      <br />
      <div id="fields form">
    
      <div class="control-group">
        
        <label  class="control-label signup-label" id="username">Username</label>
        <div class="controls ">
        <input id="id_username" type="text" name="username" maxlength="30" />
          <span class="help-block"></span>
        </div>
      </div>
    
      <div class="control-group">
        
        <label class="control-label signup-label" id="first_name">First Name</label>
        <div class="controls ">
        <input id="id_first_name" type="text" name="first_name" maxlength="50" />
          <span class="help-block"></span>
        </div>
      </div>
    
      <div class="control-group">
        
        <label class="control-label signup-label" id="last_name">Last Name</label>
        <div class="controls ">
        <input type="text" name="last_name" id="id_last_name" />
          <span class="help-block"></span>
        </div>
      </div>
      
      <div class="control-group">
        
        <label  class="control-label signup-label" id="email">Email</label>
        <div class="controls ">
        <input type="text" name="email" id="id_email" />
          <span class="help-block"></span>
        </div>
      </div>
      
      <div class="control-group">
        
        <label class="control-label signup-label" id="password_again">Account type</label>
        <div class="controls ">
        <input style="margin-top: -3px;" type="radio" name="account_type" value="staff" checked> Staff<br>
        <input style="margin-top: -3px;" type="radio" name="account_type" value="superuser"> Super User<br>
          <span class="help-block"></span>
        </div>
      </div>
    
      <div class="control-group">
        
        <label class="control-label signup-label" id="password">Password</label>
        <div class="controls ">
        <input type="password" name="password" id="id_password" />
          <span class="help-block" style="padding-left:25px;">The user can always change their password after logging in.</span>
        </div>
      </div>
    
      <div class="control-group">
        
        <label class="control-label signup-label" id="password_again">Password (again)</label>
        <div class="controls ">
        <input type="password" name="password_again" id="id_password_again" />
          <span class="help-block"></span>
        </div>
      </div>
      
    
  </div>
  <br />
  <input type="submit" style="margin-left:190px" class="btn btn-primary" value="Create" />

  </form>
  </div>
    
{% endblock %}

{% block super_js %}
<script type="text/javascript" src="/static/jquery-validation-1.9.0/jquery.validate.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#sellForm").validate({
      rules: {
        email: {
          required: true,
          email: true,
        },
        username: {
          required: true,
          maxlength: 30
        },
        first_name: {
          required: true,
          maxlength: 30
        },
        last_name: {
          required: true,
          maxlength: 30
        },
        password: {
          required: true,
          minlength: 6,
          maxlength: 22,
        },
        password_again: {
          required: true,
          equalTo: "#id_password"
        },
        account_type {
          required: true,
        }
      } 
    });
    

});
</script>

{% endblock %}